[package]
name = "wordnet-angular"
version = "0.1.0"
authors = ["John McCrae <john@mccr.ae>"]

[dependencies]
rocket = "0.3.3"
rocket_codegen = "0.3.3"
stable-skiplist = "0.1.1"
xml-rs = "0.6"
quick-error = "1.2.1"
clap = "2.26.1"
serde = "*"
serde_json = "*"
serde_derive = "*"
handlebars = "0.29.1"
rusqlite = "0.12.0"
